api_platform:
    title: StethoMe Demo API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        route_prefix: /api
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    # ApiResource folders in modules will be automatically mapped in Kernel build
    mapping:
        paths: ~
    # Swagger Web UI configuration
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
